# wallpop/Dockerfile

FROM nginx:latest
COPY ./home.html /usr/share/nginx/html/home.html
# COPY ./countermeasure.html /usr/share/nginx/html/countermeasure.html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
